// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymywyxdtffveerkknhcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteXd5eGR0ZmZ2ZWVya2tuaGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTYxNDIsImV4cCI6MjA2ODM3MjE0Mn0.vT2l3UaFhSLRgXkJjzKTyb3FiewdOgsAsMhWKNiE730";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});